title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty
twitter_username: kelaspajakwith1
instagram: kelaspajakwith

repository: kelaspajak/kelaspajak.github.io
encoding: UTF-8

collections:
  fitur:
    output: true
    permalink: /:collection/:title:output_ext
    screenshots: /assets/screenshot/logos.jpg


include:
  - _pages


defaults:
  - scope:
      path: ""
      type: fitur
    values:
      layout: detail

sass:
  load_paths:
    - _sass
    - node_modules
exclude: 
  #- node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock


plugins:
  - jekyll-mentions
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
branch: master

# Google Analytics
google_analytics: UA-146778045-2